server:
  port: 3032
  servlet:
    context-path: /home-security-service
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: HclIndia@1202
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true